#!/bin/bash

# Worktree-specific initialization script
# Sets up an isolated SLIPBOX_DATA_DIR for each concurrent CC instance/worktree
# and populates it with sample data from ~/slipbox

SOURCE_DIR="$HOME/slipbox"

# Get the current worktree directory
WORKTREE_DIR=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

# Create a unique tmp directory for this worktree
# Use tmux pane ID if available, otherwise use worktree name + PID
if [ -n "$TMUX_PANE" ]; then
    # Extract pane ID (e.g., %0, %1, etc.)
    PANE_ID=$(echo "$TMUX_PANE" | sed 's/[^0-9]//g')
    TMP_SUFFIX="pane-${PANE_ID}"
else
    # Use worktree name + PID as fallback
    WORKTREE_NAME=$(basename "$WORKTREE_DIR")
    TMP_SUFFIX="${WORKTREE_NAME}-$$"
fi

# Create isolated data directory in /tmp
export SLIPBOX_DATA_DIR="/tmp/slipbox-data-${TMP_SUFFIX}"

echo "=== Initializing Worktree Environment ==="
echo "Source: $SOURCE_DIR"
echo "Worktree: $WORKTREE_DIR"
echo "Data Dir: $SLIPBOX_DATA_DIR"
if [ -n "$TMUX_PANE" ]; then
    echo "Tmux Pane: $TMUX_PANE (ID: $PANE_ID)"
fi
echo ""

# Check if source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo "❌ Error: Source directory $SOURCE_DIR does not exist"
    exit 1
fi

# Create .env file with the isolated data directory
cat > "$WORKTREE_DIR/.env" << EOF
# Auto-generated by scripts/init.sh
# Worktree-specific isolated data directory
SLIPBOX_DATA_DIR=$SLIPBOX_DATA_DIR
EOF

echo "Created .env with SLIPBOX_DATA_DIR=$SLIPBOX_DATA_DIR"
echo ""

# Step 1: Remove the old data directory completely
echo "1. Removing old data directory..."
rm -rf "$SLIPBOX_DATA_DIR"

# Step 2: Create fresh data directory
echo "2. Creating fresh data directory..."
mkdir -p "$SLIPBOX_DATA_DIR"

# Step 3: Copy and prepare the database
if [ -f "$SOURCE_DIR/slipbox.db" ]; then
    echo "3. Preparing database..."
    
    # Checkpoint the WAL to ensure all data is in the main database file
    sqlite3 "$SOURCE_DIR/slipbox.db" "PRAGMA wal_checkpoint(TRUNCATE);" 2>/dev/null
    
    # Copy the database file
    cp "$SOURCE_DIR/slipbox.db" "$SLIPBOX_DATA_DIR/slipbox.db"
    
    # Migrate schema if needed
    echo "   Checking and migrating database schema..."
    
    # Check if we need to rename tigris_key to file_key
    HAS_TIGRIS=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM pragma_table_info('files') WHERE name='tigris_key';" 2>/dev/null || echo "0")
    if [ "$HAS_TIGRIS" = "1" ]; then
        echo "   Migrating from tigris_key to file_key..."
        sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "
            BEGIN TRANSACTION;
            ALTER TABLE files RENAME COLUMN tigris_key TO file_key;
            COMMIT;
        " 2>/dev/null
    fi
    
    # Check if tigris_bucket column exists and drop it
    HAS_BUCKET=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM pragma_table_info('files') WHERE name='tigris_bucket';" 2>/dev/null || echo "0")
    if [ "$HAS_BUCKET" = "1" ]; then
        echo "   Removing tigris_bucket column..."
        sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "
            BEGIN TRANSACTION;
            CREATE TABLE files_new (
                id TEXT PRIMARY KEY,
                original_name TEXT NOT NULL,
                mime_type TEXT NOT NULL,
                size INTEGER NOT NULL,
                file_key TEXT NOT NULL,
                uploaded_at INTEGER DEFAULT CURRENT_TIMESTAMP NOT NULL,
                note_id TEXT,
                FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE SET NULL
            );
            INSERT INTO files_new SELECT id, original_name, mime_type, size, file_key, uploaded_at, note_id FROM files;
            DROP TABLE files;
            ALTER TABLE files_new RENAME TO files;
            CREATE INDEX files_note_id_idx ON files(note_id);
            CREATE INDEX files_uploaded_at_idx ON files(uploaded_at);
            COMMIT;
        " 2>/dev/null
    fi
    
    # Clear old file entries to avoid conflicts
    echo "   Clearing old file entries..."
    sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "DELETE FROM files;" 2>/dev/null
    
    NOTE_COUNT=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM notes;" 2>/dev/null || echo "0")
    echo "   Database ready with $NOTE_COUNT notes"
else
    echo "3. No database file found - creating new one..."
    # Create a minimal database structure
    sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "
        CREATE TABLE IF NOT EXISTS notes (
            id TEXT PRIMARY KEY,
            content TEXT NOT NULL,
            created INTEGER NOT NULL,
            modified INTEGER NOT NULL
        );
        
        CREATE TABLE IF NOT EXISTS files (
            id TEXT PRIMARY KEY,
            original_name TEXT NOT NULL,
            mime_type TEXT NOT NULL,
            size INTEGER NOT NULL,
            file_key TEXT NOT NULL,
            uploaded_at INTEGER DEFAULT CURRENT_TIMESTAMP NOT NULL,
            note_id TEXT,
            FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE SET NULL
        );
        
        CREATE INDEX IF NOT EXISTS files_note_id_idx ON files(note_id);
        CREATE INDEX IF NOT EXISTS files_uploaded_at_idx ON files(uploaded_at);
    " 2>/dev/null
fi

# Step 4: Copy sample EPUB files and create database entries
echo "4. Copying sample EPUB files and creating database entries..."

EPUB_COUNT=0
EPUB_MAX=10  # Limit to 10 EPUB files for better variety in media view

for file in "$SOURCE_DIR"/*.epub; do
    if [ -f "$file" ] && [ $EPUB_COUNT -lt $EPUB_MAX ]; then
        filename=$(basename "$file")
        # Extract UUID from filename (assuming format: uuid.epub)
        file_id="${filename%.epub}"
        
        # Copy the file to flat directory
        cp "$file" "$SLIPBOX_DATA_DIR/$filename"
        
        # Get file size
        file_size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || echo "0")
        
        # Insert into database
        sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "
            INSERT INTO files (id, original_name, mime_type, size, file_key, uploaded_at)
            VALUES ('$file_id', '$filename', 'application/epub+zip', $file_size, '$filename', datetime('now'));
        " 2>/dev/null
        
        EPUB_COUNT=$((EPUB_COUNT + 1))
    fi
done

echo "   EPUB files copied and registered: $EPUB_COUNT"

# Step 5: Copy sample media files (5 of each type to keep size reasonable)
echo "5. Copying sample media files..."

copy_sample_files() {
    local extension=$1
    local mime_type=$2
    local max_count=${3:-5}
    local count=0
    
    for file in "$SOURCE_DIR"/*.$extension; do
        if [ -f "$file" ] && [ $count -lt $max_count ]; then
            filename=$(basename "$file")
            cp "$file" "$SLIPBOX_DATA_DIR/$filename"
            count=$((count + 1))
        fi
    done
    
    if [ $count -gt 0 ]; then
        echo "   Copied $count .$extension files"
    fi
}

# Copy samples of each media type
copy_sample_files "pdf" "application/pdf" 5
copy_sample_files "jpg" "image/jpeg" 5
copy_sample_files "jpeg" "image/jpeg" 5
copy_sample_files "png" "image/png" 5
copy_sample_files "gif" "image/gif" 5
copy_sample_files "mp4" "video/mp4" 5
copy_sample_files "webm" "video/webm" 5
copy_sample_files "mp3" "audio/mpeg" 5
copy_sample_files "wav" "audio/wav" 5

# Step 6: Verify the setup
echo "6. Verifying setup..."

# Count files in destination
EPUB_COUNT_DEST=$(find "$SLIPBOX_DATA_DIR" -maxdepth 1 -name "*.epub" -type f 2>/dev/null | wc -l | tr -d ' ')
MEDIA_COUNT_DEST=$(find "$SLIPBOX_DATA_DIR" -maxdepth 1 \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" -o -name "*.mp4" -o -name "*.webm" -o -name "*.mp3" -o -name "*.wav" -o -name "*.pdf" \) -type f 2>/dev/null | wc -l | tr -d ' ')
DB_EPUB_COUNT=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM files WHERE original_name LIKE '%.epub';" 2>/dev/null || echo "0")
DB_NOTE_COUNT=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM notes;" 2>/dev/null || echo "0")

echo ""
echo "=== Summary ==="
echo "Database:"
echo "  - Notes: $DB_NOTE_COUNT"
echo "  - EPUB entries: $DB_EPUB_COUNT"
echo ""
echo "Files on disk:"
echo "  - EPUBs: $EPUB_COUNT_DEST"
echo "  - Other media files: $MEDIA_COUNT_DEST"

# Calculate directory size
DEST_SIZE=$(du -sh "$SLIPBOX_DATA_DIR" 2>/dev/null | cut -f1)
echo ""
echo "Directory size: $DEST_SIZE"

if [ "$DB_EPUB_COUNT" = "$EPUB_COUNT_DEST" ] && [ -f "$SLIPBOX_DATA_DIR/slipbox.db" ]; then
    echo ""
    echo "✅ Success! Development data directory has been reset."
    echo "   Database and files are in sync."
    echo "   $EPUB_COUNT_DEST EPUB files are ready to read."
    echo "   $MEDIA_COUNT_DEST sample media files available."
else
    echo ""
    echo "⚠️  Warning: File count mismatch!"
    echo "   Database has $DB_EPUB_COUNT EPUB entries"
    echo "   Directory has $EPUB_COUNT_DEST EPUB files"
fi

echo ""
echo "✅ Worktree initialization complete!"
echo "   Each terminal in this worktree will use: $SLIPBOX_DATA_DIR"
echo "   Run 'npm run dev' to start the development server."