#!/bin/bash

# Worktree-specific initialization script
# Sets up an isolated SLIPBOX_DATA_DIR for each concurrent CC instance/worktree
# and populates it with sample data from ~/slipbox

SOURCE_DIR="$HOME/slipbox"

# Get the current worktree directory
WORKTREE_DIR=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

# Get the current branch name
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || "unknown")

# Create a unique tmp directory for this worktree
if [ -n "$TMUX_PANE" ]; then
    # Extract pane ID (e.g., %0, %1, etc.)
    PANE_ID=$(echo "$TMUX_PANE" | sed 's/[^0-9]//g')
    TMP_SUFFIX="pane-${PANE_ID}"
else
    # Use worktree name + PID as fallback
    WORKTREE_NAME=$(basename "$WORKTREE_DIR")
    TMP_SUFFIX="${WORKTREE_NAME}-$$"
fi

# Create isolated data directory in /tmp
export SLIPBOX_DATA_DIR="/tmp/slipbox-data-${TMP_SUFFIX}"

echo "=== Initializing Environment ==="
echo "Branch: $CURRENT_BRANCH"
echo "Source: $SOURCE_DIR"
echo "Worktree: $WORKTREE_DIR"
echo "Data Dir: $SLIPBOX_DATA_DIR"
if [ -n "$TMUX_PANE" ]; then
    echo "Tmux Pane: $TMUX_PANE (ID: $PANE_ID)"
fi
echo ""

# Check if source directory exists
if [ ! -d "$SOURCE_DIR" ]; then
    echo "❌ Error: Source directory $SOURCE_DIR does not exist"
    exit 1
fi

# Create .env file with the isolated data directory
cat > "$WORKTREE_DIR/.env" << EOF
# Auto-generated by scripts/init.sh
# Worktree-specific isolated data directory
SLIPBOX_DATA_DIR=$SLIPBOX_DATA_DIR
EOF

echo "Created .env with SLIPBOX_DATA_DIR=$SLIPBOX_DATA_DIR"
echo ""

# Step 1: Remove the old data directory completely
echo "1. Removing old data directory..."
rm -rf "$SLIPBOX_DATA_DIR"

# Step 2: Create fresh data directory
echo "2. Creating fresh data directory..."
mkdir -p "$SLIPBOX_DATA_DIR"

# Step 3: Create fresh database and run migrations
echo "3. Creating fresh database with migrations..."
cd "$WORKTREE_DIR"
npm run db:migrate 2>/dev/null || {
    echo "   Migration failed, falling back to direct SQL..."
    # Apply the migration directly if npm command fails
    sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" < "$WORKTREE_DIR/src/db/migrations/0000_initial_schema.sql"
}

NOTE_COUNT=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM notes;" 2>/dev/null || echo "0")
echo "   Database ready with $NOTE_COUNT notes (should be 0)"

# Step 3.5: Generate sample Roman Empire notes
echo "3.5. Generating 25 Roman Empire notes..."
bun "$WORKTREE_DIR/scripts/generate-roman-notes.js"
NOTE_COUNT=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM notes;" 2>/dev/null || echo "0")
echo "   Database now has $NOTE_COUNT notes"

# Step 4: Copy sample EPUB files and create database entries
echo "4. Copying sample EPUB files and creating database entries..."

EPUB_COUNT=0
EPUB_MAX=10  # Limit to 10 EPUB files for better variety in media view

for file in "$SOURCE_DIR"/*.epub; do
    if [ -f "$file" ] && [ $EPUB_COUNT -lt $EPUB_MAX ]; then
        filename=$(basename "$file")
        # Extract UUID from filename (assuming format: uuid.epub)
        file_id="${filename%.epub}"
        
        # Copy the file to flat directory
        cp "$file" "$SLIPBOX_DATA_DIR/$filename"
        
        # Get file size
        file_size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || echo "0")
        
        # Insert into database
        sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "
            INSERT INTO files (id, original_name, mime_type, size, file_key, uploaded_at)
            VALUES ('$file_id', '$filename', 'application/epub+zip', $file_size, '$filename', datetime('now'));
        " 2>/dev/null
        
        EPUB_COUNT=$((EPUB_COUNT + 1))
    fi
done

echo "   EPUB files copied and registered: $EPUB_COUNT"

# Step 5: Copy sample media files (5 of each type to keep size reasonable)
echo "5. Copying sample media files..."

copy_sample_files() {
    local extension=$1
    local mime_type=$2
    local max_count=${3:-5}
    local count=0
    
    for file in "$SOURCE_DIR"/*.$extension; do
        if [ -f "$file" ] && [ $count -lt $max_count ]; then
            filename=$(basename "$file")
            cp "$file" "$SLIPBOX_DATA_DIR/$filename"
            count=$((count + 1))
        fi
    done
    
    if [ $count -gt 0 ]; then
        echo "   Copied $count .$extension files"
    fi
}

# Copy samples of each media type
copy_sample_files "pdf" "application/pdf" 5
copy_sample_files "jpg" "image/jpeg" 5
copy_sample_files "jpeg" "image/jpeg" 5
copy_sample_files "png" "image/png" 5
copy_sample_files "gif" "image/gif" 5
copy_sample_files "mp4" "video/mp4" 5
copy_sample_files "webm" "video/webm" 5
copy_sample_files "mp3" "audio/mpeg" 5
copy_sample_files "wav" "audio/wav" 5

# Step 6: Verify the setup
echo "6. Verifying setup..."

# Count files in destination
EPUB_COUNT_DEST=$(find "$SLIPBOX_DATA_DIR" -maxdepth 1 -name "*.epub" -type f 2>/dev/null | wc -l | tr -d ' ')
MEDIA_COUNT_DEST=$(find "$SLIPBOX_DATA_DIR" -maxdepth 1 \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" -o -name "*.mp4" -o -name "*.webm" -o -name "*.mp3" -o -name "*.wav" -o -name "*.pdf" \) -type f 2>/dev/null | wc -l | tr -d ' ')
DB_EPUB_COUNT=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM files WHERE original_name LIKE '%.epub';" 2>/dev/null || echo "0")
DB_NOTE_COUNT=$(sqlite3 "$SLIPBOX_DATA_DIR/slipbox.db" "SELECT COUNT(*) FROM notes;" 2>/dev/null || echo "0")

echo ""
echo "=== Summary ==="
echo "Database:"
echo "  - Notes: $DB_NOTE_COUNT"
echo "  - EPUB entries: $DB_EPUB_COUNT"
echo ""
echo "Files on disk:"
echo "  - EPUBs: $EPUB_COUNT_DEST"
echo "  - Other media files: $MEDIA_COUNT_DEST"

# Calculate directory size
DEST_SIZE=$(du -sh "$SLIPBOX_DATA_DIR" 2>/dev/null | cut -f1)
echo ""
echo "Directory size: $DEST_SIZE"

if [ "$DB_EPUB_COUNT" = "$EPUB_COUNT_DEST" ] && [ -f "$SLIPBOX_DATA_DIR/slipbox.db" ]; then
    echo ""
    echo "✅ Success! Development data directory has been reset."
    echo "   Database and files are in sync."
    echo "   $EPUB_COUNT_DEST EPUB files are ready to read."
    echo "   $MEDIA_COUNT_DEST sample media files available."
else
    echo ""
    echo "⚠️  Warning: File count mismatch!"
    echo "   Database has $DB_EPUB_COUNT EPUB entries"
    echo "   Directory has $EPUB_COUNT_DEST EPUB files"
fi

echo ""
echo "✅ Initialization complete!"
echo "   Data directory: $SLIPBOX_DATA_DIR"
echo "   Run 'npm run dev' to start the development server."