#!/bin/bash

# Worktree-specific initialization script
# Called by ~/configs/bin/vibe to set up an isolated SLIPBOX_DATA_DIR
# for each concurrent CC instance/worktree

# Get the current worktree directory
WORKTREE_DIR=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

# Create a unique tmp directory for this worktree
# Use tmux pane ID if available, otherwise use worktree name + PID
if [ -n "$TMUX_PANE" ]; then
    # Extract pane ID (e.g., %0, %1, etc.)
    PANE_ID=$(echo "$TMUX_PANE" | sed 's/[^0-9]//g')
    TMP_SUFFIX="pane-${PANE_ID}"
else
    # Use worktree name + PID as fallback
    WORKTREE_NAME=$(basename "$WORKTREE_DIR")
    TMP_SUFFIX="${WORKTREE_NAME}-$$"
fi

# Create isolated data directory in /tmp
export SLIPBOX_DATA_DIR="/tmp/slipbox-data-${TMP_SUFFIX}"

echo "=== Initializing Worktree Environment ==="
echo "Worktree: $WORKTREE_DIR"
echo "Data Dir: $SLIPBOX_DATA_DIR"
if [ -n "$TMUX_PANE" ]; then
    echo "Tmux Pane: $TMUX_PANE (ID: $PANE_ID)"
fi
echo ""

# Create .env.local file with the isolated data directory
cat > "$WORKTREE_DIR/.env.local" << EOF
# Auto-generated by scripts/init.sh
# Worktree-specific isolated data directory
SLIPBOX_DATA_DIR=$SLIPBOX_DATA_DIR
EOF

echo "Created .env.local with SLIPBOX_DATA_DIR=$SLIPBOX_DATA_DIR"

# Run reset-datadir.sh to populate the isolated directory
echo ""
echo "Setting up isolated data directory..."
"$WORKTREE_DIR/scripts/reset-datadir.sh"

echo ""
echo "✅ Worktree initialization complete!"
echo "   Each terminal in this worktree will use: $SLIPBOX_DATA_DIR"
echo "   Run 'npm run dev' to start the development server."